name: cloud formation deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::9632-5872-2155:role/cloudformation@123
          aws-region: us-east-1 # Change if needed

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yaml \
            --stack-name test-stack-name \
            --capabilities CAPABILITY_NAMED_IAM
